# Configuration file
#
#

general:
  process:
    app_name: "Order Monit Service"
    ontop: false # if true the process is not sent to the background
    log_output: true # writes an output file, good option for a background process
    backtrace: true
  running_cycle_frequency: 120 #seconds, the same time used to verify new orders
  number_of_integration_retries: 2

email:
  smtp:
    address: 'smtp.gmail.com'
    port: 587
    enable_starttls_auto: true
    user_name: 'felipe.japm'
    password: 'JVtxROb0W5hFWwLPEBeqrp4i'
    authentication: :plain
  subscribers:
    - felipe.japm@gmail.com  

integration_server:
  #host: "homolog.olook.com.br"
  host: "localhost"
  #port: 13630
  port: 22
  #username: "root"
  username: "felipe"
  password: "s8872849"
  #rails_root: "/srv/olook/current"
  rails_root: "/home/felipe/projetos/Olook/olook"

database:
  adapter: mysql2
  database: olook_development
  username: root
  password: 'olook123'
  host: localhost